### PR TITLE
Handle 'not_found' peer for chronicle_config.

### PR DESCRIPTION
**Pull request by hareen-kancharla**
Find more details on issue https://github.com/couchbase/chronicle/issues/6

### CODE REVIEW

**Comment by timofey-barmin** [comment]
@hareen-kancharla
Have you tried reproducing the issue and does the suggested fix help?

**Comment by hareen-kancharla** [comment]
@timofey-barmin: Yup. I reproduced it via chronicled (https://github.com/couchbase/chronicle/tree/master/examples/chronicled) and verified the fix.

**Comment by timofey-barmin** [comment]
Do you understand what kind of incompatibility it may cause? I don't think I understand it very well.

**Comment by dave-finlay** [comment]
I think the incompatibility is that chronicle_rsm used to crash when it was handling replies and they were from nodes that were no longer part of the config. Now the replies from nodes that are no longer part of the config will be ignored. The old behavior was "catastrophic" as Aliaksei put it, so it's almost certainly the case that no one was relying upon it. So even though strictly not backwards compatible, probably safe to go forward with.

**Comment by timofey-barmin** [comment]
Got it, thanks! The fix LGTM.

**Comment by aartamonau** [comment]
I don't remember all too well how ns_server manages the chronicle topology. But I would attempt to reproduce *with* ns_server. It's probably a lot harder (if not impossible) to reproduce this issue by only using the APIs that ns_server exposes.

**Comment by hareen-kancharla** [comment]
In general it seems difficult for this happen from within ns_server but can definitely happen. Here's my current understanding:

1. chronicle_master:remove_peer(node()) on the master node leaves the operation_key() in chronicle_kv.
2. The new master re-runs chronicle_master:remove_peer(OldMaster) operation when it finds the delegated operation_key.

Most often a new master will re-run remove_peer(OldMaster) operation - but there is one tiny window in which OldMaster might re-run remove_peer operation. For example:

a. OldMaster removes itself from nodes_wanted list in step 1.
b. mb_master receives peers_changed notification on OldMaster and hasn't gotten yet to shuts down master_sup.

Now, if chronicle_master crashes (and restarts) between step a. and step b., it is possible that we'll re-run the remove_peer operation on the OldMaster during chronicle_master:init/1. I haven't really been able to reproduce this because in general the window between the two remove_peer(node()) operations has to be greater than 100 msecs (in my testing).

For example: 
1. These lead to a crash as mentioned in the original issue  

(sleep for 100 msecs before the second operation). 
`
(chronicle_1@127.0.0.1)1> spawn(fun () -> chronicle:remove_peer(node()) end), timer:sleep(100), spawn(fun () -> chronicle:remove_peer(node()) end).
<0.185.0>
`

('chronicle_2' is removing 'chronicle_1' twice)
`
(chronicle_1@127.0.0.1)1> Node = node(), spawn('chronicle_2@127.0.0.1', fun () -> chronicle:remove_peer(Node) end), spawn('chronicle_2@127.0.0.1', fun () -> chronicle:remove_peer(Node) end).
`

2. These doesn't.

(sleep for 150 msecs before the second operation). 
`
(chronicle_1@127.0.0.1)1> spawn(fun () -> chronicle:remove_peer(node()) end), timer:sleep(150), spawn(fun () -> chronicle:remove_peer(node()) end).
`

(chronicle_1 is being removed by both itself and chronicle_2).
`
(chronicle_1@127.0.0.1)1> Node = node(), spawn(fun () -> chronicle:remove_peer(Node) end), spawn('chronicle_2@127.0.0.1', fun () -> chronicle:remove_peer(Node) end).
`

^I think I just got lucky here - if the second call on the remote node happened within the 100 msecs window it would have crashed.

**Pull request merged**
